### PR TITLE
Add option to generate optional checksums

### PR DESCRIPTION
**Pull request by amCap1712**
This PR aims to solve #4.

### CODE REVIEW

**Comment by amCap1712** [comment]
Hi! I have begun the preliminary work on this and had a couple of questions.
1)  https://github.com/spdx/spdx-maven-plugin/blob/20566304bd2f11914073e24d57abb7ae56ddba83/src/main/java/org/spdx/maven/SpdxFileCollector.java#L73-L86
The `MessageDigest` instance is cached here for later reuse. I see that the checksum method is being used only at 3-4 places and that too outside a loop. I do not think caching here is useful. If we remove this and get a new instance every time, we can further unify the code for generating SHA1 and other optional checksums.

2)https://github.com/spdx/spdx-maven-plugin/blob/20566304bd2f11914073e24d57abb7ae56ddba83/src/main/java/org/spdx/maven/SpdxFileCollector.java#L593-L602
We can simplify this part somewhat by using `Files.readAllBytes`. However, as the name suggests it reads the entire file into the memory at once. Could this be an issue while generating the checksum for the archives ? If not, I'll go ahead and make the change to simplify it.

**Comment by goneall** [comment]
> If we remove this and get a new instance every time, we can further unify the code for generating SHA1 and other optional checksums.

I think it is reasonable to remove the caching if it helps the code structure

> Could this be an issue while generating the checksum for the archives ? If not, I'll go ahead and make the change to simplify it.

I don't think it would be an issue - go ahead and simplify

**Review by goneall — COMMENTED** [review]
Please extend the unit tests to test the additional optional checksums

**Comment by amCap1712** [comment]
@goneall I had a doubt for which files do the checksum has to be generated. I have made the changes and added the test. I tried it a sample project but it doesn't work. I tried to debug and found that its because the `target/classes` directory is being passed as the file for checksums. I was wondering for which files should the checksum be calculated ?

**Comment by amCap1712** [comment]
@goneall I had a doubt for which files do the checksum has to be generated. I have made the changes and added the test. I tried it a sample project but it doesn't work. I tried to debug and found that its because the `target/classes` directory is being passed as the file for checksums. I was wondering for which files should the checksum be calculated ?

**Comment by goneall** [comment]
> I tried to debug and found that its because the target/classes directory is being passed as the file for checksums. I was wondering for which files should the checksum be calculated ?

The checksums should be applied to any files which are included as part of the build - generally the source files and any binary library files used as input.  It should not include any generated out output file.

The code that manages this is the [SpdxFileCollector classs](https://github.com/spdx/spdx-maven-plugin/blob/master/src/main/java/org/spdx/maven/SpdxFileCollector.java).

I took a quick look at the PR and I couldn't spot the problem - it doesn't look like the changes you made should impact which files are collected.

You might try setting a breakpoint and compare before the PR and after and see what may be different.

**Comment by amCap1712** [comment]
I tested with the project with a plugin version without these changes and I found
`[WARNING] Unable to collect sha1 value for classes:IO getting file content while calculating the SHA1` in the logs. I think I may not have setup the test project correctly, hence the error.

**Comment by amCap1712** [comment]
@goneall I think the PR is now ready to be reviewed.

**Review by goneall — APPROVED** [review]

**Comment by goneall** [comment]
Thanks @amCap1712

**Pull request merged**
